apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: v2
    {{- if .Values.ratings.fault.enabled }}
    fault:
      abort:
        httpStatus: {{ .Values.ratings.fault.abort.httpStatus }}
        percentage:
          value: {{ .Values.ratings.fault.abort.percentage }}
    {{- end }}
---